### ISSUE TITLE
DATABASE_ERROR - description: no type information

### ISSUE THREAD

**Issue by phuicy** [Kinovarobotics/kortex#100]
## Description

I have upgraded the API of the robot to v2.3 from v2.2, and now get this fault on connection.

```
terminate called after throwing an instance of 'Kinova::Api::KDetailedException'
  what():  Device error, Error sub type=DATABASE_ERROR => <srv: 2, fct: 44, msgType: 3>
description: no type information
```

## Version

![image](https://user-images.githubusercontent.com/4666094/156778523-87a374dc-55cf-4288-b6af-c39ebcf212e2.png)

**Comment by phuicy** [comment]
```
  auto action_type = Base::RequestedActionType();
  action_type.set_action_type(Base::REACH_JOINT_ANGLES);
  auto action_list = base->ReadAllActions(action_type);
```

failing to get Action list

**Comment by felixmaisonneuve** [comment]
Hi @phuicy,

A factory reset of your arm should fix your issue. 
You can do this from the web app in Configurations->Robot->Arm->Base->Reset Factory Settings

Just be carefull, it will wipe all the protection zones and actions that are present. 

Regards,
Felix

**Comment by phuicy** [comment]
Initial testing shows this as resolved.

thanks,
Guy
