### ISSUE TITLE
Configuration of the 6th Actuator on Kinova Gen3-lite robot is not available

### ISSUE THREAD

**Issue by karinaGarcia98** [Kinovarobotics/kortex#115]
## Description

On the Kinova Gen 3 lite robot, there is an error occurring when attempting to access the configuration of the 6th actuator, specifically.
For instance, when trying to read the active control loops bitmask value of the 6th actuator makes the following error to occur: 
`API error: Server protocol error, Error sub type = UNSUPPORTED_SERVICE -> <srv: 10, fct: 8, msgType: 3>`
Also, when trying to change the control mode (i.e. from Position to any other), the following error occurs:
`API error: Internal error, Error sub type=SUB-ERROR-NONE -> <srv: 10, fct: 7, msgType: 3>`

## Version

Kortex API : 2.3.0-r.34
Kortex Device : Kinova Gen3 lite 
Firmware version: 2.3.1-r.3 (Bundle), 2.3.2-r.1 (Actuators 1 - 6)

## Steps to reproduce

1. Using the 108-Gen3_torque_control/01-torque_control_cyclic.cpp from the examples as a base.
2. Add the following code (either one of them) before the 1ms loop on the example_cyclic_torque_control function, right after sending the first frame.
3. Build and execute.

## Code example

```
     // --- Set actuators in CURRENT CONTROL mode ---
            auto control_mode_message = k_api::ActuatorConfig::ControlModeInformation();
            control_mode_message.set_control_mode(k_api::ActuatorConfig::ControlMode::CURRENT);
         std::cout << "Setting actuator 1 in CURRENT control mode"<< std::endl;
            actuator_config->SetControlMode(control_mode_message, 1);
         std::cout << "Setting actuator 5 in CURRENT control mode"<< std::endl;   
            actuator_config->SetControlMode(control_mode_message, 5);
         std::cout << "Setting actuator 6 in CURRENT control mode"<< std::endl;   
            actuator_config->SetControlMode(control_mode_message, 6);
```
```
     // Active control loops
        // Get and print the bitmask value of each actuator's active control loops        
        auto activeControlLoops = k_api::ActuatorConfig::ControlLoop();

        activeControlLoops = actuator_config->GetActivatedControlLoop(1);
        std::cout << "Active Control Loops on joint 1 : " << activeControlLoops.control_loop() << std::endl;

        activeControlLoops = actuator_config->GetActivatedControlLoop(2);
        std::cout << "Active Control Loops on joint 2 : " << activeControlLoops.control_loop() << std::endl;

        activeControlLoops = actuator_config->GetActivatedControlLoop(3);
        std::cout <<  "Active Control Loops on joint 3 : " << activeControlLoops.control_loop() << std::endl;

        activeControlLoops = actuator_config->GetActivatedControlLoop(4);
        std::cout << "Active Control Loops on joint4 : " << activeControlLoops.control_loop() << std::endl;

        activeControlLoops = actuator_config->GetActivatedControlLoop(5);
        std::cout <<  "Active Control Loops on joint 5 : " << activeControlLoops.control_loop() << std::endl;

        activeControlLoops = actuator_config->GetActivatedControlLoop(6);
        std::cout << "Active Control Loops on joint 6 : "<< activeControlLoops.control_loop() << std::endl;
```

## Expected behavior

I would expect to be able to configure and read the configuration of the 6th actuator the same way as I do with the other (1 - 5) actuators.

## Any other information

I have tried the same code with the 7 actuators of the Kinova Gen 3 (7 DoF) robot and I have not gotten a similar mistake.

**Comment by Elinglet** [comment]
Hello Karina!

I was able to reproduce the issue. Apparently it is caused because the ordering of the motors is altered by the gripper's.

When changing 6 for 7, it works perfectly.

Cheers!
