### ISSUE TITLE
Suport for osx

### ISSUE THREAD

**Issue by rleontienrl** [Kinovarobotics/kortex#118]
Hi,

I am a researcher trying to use the KG3 arm. I was trying to compile software that uses the kortex api and unfortunately I realized there is no support for osx. Is there a plan for that? Has anyone been successful at it? 

Thank you!

**Comment by felixmaisonneuve** [comment]
Hi @rleontienrl,

Doesn't OSX run on the linux kernel? Have you tried using the linux build of the API?

If you did and it did not work, I don't think I can help you much more. It is not planned at the moment the add API support for OSX.
Sorry

Regards,
Felix
