### ISSUE TITLE
Example of Inverse Kinematics

### ISSUE THREAD

**Issue by JaeYoungLee79** [Kinovarobotics/kortex#123]
Dear Sir

Example of forward kinematics is calculated without the current joint vlaue.
User's desire input value to the example, it is calculated any joint values.

But, the example of inverse kinematics,
Only running the cartesian values which is calculated by the input of current joint value.

If user's desire input values, it is not calculated below is example code lines
======================================================================
def example_inverse_kinematics(base):
    # get robot's pose (by using forward kinematics)
    try:
        input_joint_angles = base.GetMeasuredJointAngles()
        pose = base.ComputeForwardKinematics(input_joint_angles) <<<---- Must be calculated?
<<<< ----- I just want to input as my own values (x, y, z, theta_x, theta_y, theta_z)

    except KServerException as ex:
        print("Unable to get current robot pose")
        print("Error_code:{} , Sub_error_code:{} ".format(ex.get_error_code(), ex.get_error_sub_code()))
        print("Caught expected error: {}".format(ex))
        return False
======================================================================

Do you know IK API options?
Or I guess that it have to release the lmit of current workspace with robot?

Thanks
Best Regards

**Comment by felixmaisonneuve** [comment]
Hi @JaeYoungLee79,

I am not sure I fully understand what you want, so I will try to explain the inverse kinematics function and, hopefully, it will clear things out for you.

The inverse kinematics function uses the `IKData` that contains a cartesian pose, the one you want to compute the IK on, and a guess, that helps you to find the correct configuration for the arm on the solution you want. The forward kinematics computation is easy, you specify an angle value for each joint and you find the final XYZ coordinates. The inverse kinematics computation is harder. A single XYZ position can be achieved by multiple configurations of joint angles. So, for the same cartesian input, you have multiple solutions. This is why you need to provide a guess (a list of joint values). It will provide a reference point duration computation and the inverse kinematics computation will return the closest solution to the guess. 

In our example, we use `ComputeForwardKinematics` to get the cartesian pose that corresponds to the joint values we want (and we use `GetMeasuredJointAngles` to get the joint values, but you can use whatever `JointAngles` you want). We then uses these `JointAngles` again (minus 1 degree) for the guess. 

I am not sure what IK API options you want or what it has to do with the robot's workspace. 
Can you be more specific on that?

Best,
Felix
