### ISSUE TITLE
Support for Robotiq vacuum grippers

### ISSUE THREAD

**Issue by jimmyyhwu** [Kinovarobotics/kortex#138]
Does the Kortex API support [Robotiq vacuum grippers](https://robotiq.com/products/vacuum-grippers)?

**Comment by felixmaisonneuve** [comment]
Hi @jimmyyhwu

> Does the Kortex API support Robotiq vacuum grippers?
Partially.

If you install a Robotiq Vacuum gripper and you select one of the 2F gripper in the WebApp, the open or close command (not sure which one), will activate the vacuum. 

However, if the vacuum is not tight enough or the succion cup is not correctly placed, there is a risk that the vacuum will use too much current. That will lead to major faults and you might have to reboot the arm to recover from it. 

Hope this helps,
Felix
