### ISSUE TITLE
Clarification needed: Automatic Power on for Gen3

### ISSUE THREAD

**Issue by alexswerner** [Kinovarobotics/kortex#139]
## Description
The API release 2.5.0 is suppose to bring "Automatic Power On variant of the Gen3
". Does "variant" mean that new hardware is necessary which is supported by the new version of the API? Or does it otherwise mean that this is a configurable option?

As instructed in the commit message, I read the relase notes at: file:///home/awerner/Downloads/EN-eRN-001-Gen3-Ultralight-release-notes.pdf
This makes me think this is a hardware variant. Which one is correct?

Thanks!

## Version
Gen3 with API 2.5.0 

## Steps to reproduce
1. Update
2. Try to find an option to enable automatic start in the web interface

**Comment by felixmaisonneuve** [comment]
Hi @alexswerner,

The automatic power-on arms have a different hardware.

You can use the 2.5.0 API on Gen3 arms without the hardware modification, but you won't be able to use the automatic power-on feature. 
Also, with Automatic power-on arms, you won't be able to use APIs older than 2.5.0

Best,
Felix
