### ISSUE TITLE
Increase velocity limit through high level API to 100Deg/s.

### ISSUE THREAD

**Issue by sjhansen3** [Kinovarobotics/kortex#14]
## Summary

Allow for 100 deg/s commanded velocities through the high level API. Currently the commanded values are limited to 50 deg/s. This limits control performance.

## Use case

Increased control performance while maintaining safeties implemented by the high level API.

## Alternative
Send the commands at 40Hz.

## Possible issues

Crappy control performance at 40Hz.

**Comment by alexvannobel** [comment]
Hi Stephen,

In the upcoming months, we will indeed be looking at ways (both mechanical and software) to allow for higher commanded velocities through the high-level API. 

Thanks a lot for the feedback.
Cheers,
Alex

**Comment by alexvannobel** [comment]
Hi @sjhansen3 ,

This is to let you know that the soft speed and acceleration limits are now configurable as of release 2.2 for Gen3, and the hard limits have been increased to 80 deg/s for the big actuators and to 70 deg/s for the small actuators. The Cartesian twist hard limits are now 50 cm/s (linear) and 100 deg/s (angular).

It is not currently in the roadmap to make the Gen3 arm faster (so 100 deg/s is not planned for now), but I'll let the issue open anyway to let you know in the future if there are improvements in the Gen3 joint or Cartesian speed.

Best regards,
Alex

**Comment by sjhansen3** [comment]
Awesome!

**Comment by martinleroux** [comment]
Tests were recently run to validate whether it would be possible to increase the twist hard limits and it was determined that limitations of the hardware will prevent us from making it happen. I will therefore close this issue.
