### ISSUE TITLE
red light on ROBOTIQ gripper

### ISSUE THREAD

**Issue by pouyan-asg** [Kinovarobotics/kortex#140]
## Description

Hello,

I have a quick question. From today and without any failure or damage, the Gen3 robot can not recognise the "Robotiq" gripper. I rebooted some different times from configurations==>Robot==>Product, but it did not change. Also, I uninstalled the gripper, installed it again, and did the same procedure.
The light on the gripper is permanent red. 

Do you have any idea about its solution?

If you need more information, let me know.

Thank you very much

## Version

Web App version: 2.9.0-r.15
Web Client API Version: 2.3.0-r.43

## Expected behavior

Recognizing the gripper and using/controlling the Robotic gripper is the usual way.

## Any other information

I should tell you that the robot has not hit anything or there was no physical issue.

**Comment by felixmaisonneuve** [comment]
For future reference,
@pouyan-asg can you describe what the issue was and how you solved it?
I suspect the Robotiq gripper was the issue because of the red LED, is it correct?

Thank you,
Felix
