### ISSUE TITLE
question： I want to know how set tool tcp（tool  transform）in program with c++. can you help me write a exmple program(gen3 7dof)

### ISSUE THREAD

**Issue by wentianheshi** [Kinovarobotics/kortex#142]
[##]([url](url)) Summary

A short description of the requested feature.

## Use case

Why is this feature needed?

What are the use case covered by this feature?

## Alternative

Do you have an idea how on how best to implement this enhancement?

If this feature is not implemented, do you have a workaround?

## Possible issues

Anything that could be affected by the new feature.

## Additional context

Any other information you would like us to know about the requested enhancement.
![image](https://user-images.githubusercontent.com/38513139/210916818-bbb3bc6e-45fb-4808-a2a3-be8ec12eeda0.png)

**Comment by felixmaisonneuve** [comment]
Hi @wentianheshi,

The [ToolConfiguration](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/messages/ControlConfig/ToolConfiguration.md#) class is part of the [ControlConfig](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/summary_pages/ControlConfig.md) client. 

To set your tool, it will be something like
```c++
#include <ControlConfigClientRpc.h>
...
auto control_config = new k_api::ControlConfig::ControlConfigClient(router);
auto tool_config = control_config->GetToolConfiguration();

// Change your tool_config here
...

control_config->SetToolConfiguration(tool_config);
``` 

Best Regards,
Felix

**Comment by wentianheshi** [comment]
Hi felix,
thank you very much. I get 
Best Regards,
Wentianheshi
