### ISSUE TITLE
huw to get the Jacob mat of gen3

### ISSUE THREAD

**Issue by WHuangEI** [Kinovarobotics/kortex#148]
## Summary

I am working on the controlling and planning of gen3 and i need to know the Jacobi matrix eagerly. Can the official provide the it ?

## Use case

Why is this feature needed?

What are the use case covered by this feature?

## Alternative

Do you have an idea how on how best to implement this enhancement?

If this feature is not implemented, do you have a workaround?

## Possible issues

Anything that could be affected by the new feature.

## Additional context

Any other information you would like us to know about the requested enhancement.

**Comment by felixmaisonneuve** [comment]
Hi @WHuangEI,

Here is another issue with the same question : #70 

> Unfortunately, we do not provide our Jacobian matrix.
> You can use the third party library [Robotics Library](https://www.roboticslibrary.org/). However, we use a custom calibration to get a highier degree of precision that you won't be able to achieve using this library.
> I can also link this article that explains the algorithm used by our API :
Phuoc, L. M., Lee, S. H., Kim, H. M., & Martinet, P. (2008). Damped least square based genetic algorithm with Gaussian distribution of damping factor for singularity-robust inverse kinematics. Journal of Mechanical Science and Technology, 22(7), 1330-1338.

Best Regards,
Felix
