### ISSUE TITLE
Use a standard .deb package for protobuf

### ISSUE THREAD

**Issue by sjhansen3** [Kinovarobotics/kortex#15]
## Summary

Currently installing kortex requires installing a frozen version of protobuf from source - this is quite a pain. It adds 30 minutes to our builds which affects our automated tests and setup times. It would be far preferrable for you guys to use a standard version of protobuf and not a frozen one.

## Use case

In order for Kortex and Kinova gen3 to become used easily and widespread you shouldn't require people to install from source - I imagine it will cost you in support  time as well. Its not common that everyone will be able to install protobuf from source, we ran into a few hiccups in the compilation and dependencies - these are now fixed, but it still leaves us with an additional 30 minutes of compilation per build :/

## Alternative

Build it from source.

**Comment by alexvannobel** [comment]
Hi Stephen,

As explained in Kinovarobotics/ros_kortex#23, the Protobuf library was combined to the kortex_api library in the latest release (1.1.6), so it's now required anymore to install Protobuf to build and run the examples in this repo.
I'll update the other issue concerning the Protobuf version we use and close this one.  

Thanks again for the feedback,
Cheers,
Alex
