### ISSUE TITLE
Needs of rotor inertia value for efficient torque control on Gen3 robots

### ISSUE THREAD

**Issue by mathieu-celerier** [Kinovarobotics/kortex#157]
I am currently working on Kinova Gen3 using torque control.
To improve the torque control I would like to include the dynamical effect of rotor inertia in my framework.

Is it possible to know what motors are used in the Gen3 robot?

If not, could you please provide the following:
- Rotor inertia
- Gear Ratio

For both:
- Large actuators
- Small actuators

Best regards,

Mathieu Celerier

**Comment by felixmaisonneuve** [comment]
Hi @mathieu-celerier,

We cannot share the actuator model, but you can contact the support team at support@kinova.ca and they might be able to share the inertia and gear ratio

Regards,
Felix

**Comment by juandavid212** [comment]
Hi @mathieu-celerier,
Did you manage to implement this efficient torque control? I'm planning to implement something similar. Would you mind sharing your code?
