### ISSUE TITLE
Singularity Avoidance

### ISSUE THREAD

**Issue by pouyan-asg** [Kinovarobotics/kortex#161]
## Summary

I have a general question. Is there any inherit feature for the Gen3 robot to avoid singularity? In some Cartesian mode, I need the robot to pass singularities without stopping.

Thank you in advance

**Comment by felixmaisonneuve** [comment]
Hi @pouyan-asg,

Yes, the arm is supposed to deviate slightly from its trajectory to avoid going into singularities when moving in cartesian mode. 

Best,
Felix

**Comment by felixmaisonneuve** [comment]
exactly. You should not have anything to do
