### ISSUE TITLE
Modbus Emergency Stop and Reset

### ISSUE THREAD

**Issue by BBlumhofer** [Kinovarobotics/kortex#170]
## Description
I am forced to use the Modbus TCP connection to the robot as it will be later controlled by a PLC. I built up a testing setup using pymodbus on a laptop. The example script works well for me but I can not activate reliable the emergency stop and can not reset the robot at all. I tried different methods to send the message. I attached a small code snippet with both commands. Can you explain me where my coding fault is or if it is a bug on the robot

## Version
Robot:  Gen3 Ultra Lightweight Robot 6DOF
Firmware:  2.4.0-3

## Steps to reproduce

run the code in python

## Code example

```
#! /usr/bin/env python3

import time
from pymodbus.client.sync import ModbusTcpClient


# Default modbus port.
PORT = 502

# IP address of the robot that holds the modbus slave.
IP_ADDRESS = '192.168.1.10'


def reset():
    # instantiate modbus client connection
    client = ModbusTcpClient(IP_ADDRESS, PORT)
    assert client.connect(), "Unable to connect to the slave"

    client.write_coil(0, True)
    time.sleep(2)

    client.write_coil(2, False)

    client.close()


if __name__ == "__main__":
    reset()

```

## Expected behavior

- Activate emergency stop
- wait 2s
- reset robot to be able to start moving again

**Comment by BBlumhofer** [comment]
Hi Felix, 

There are two issues. At first, the E-Stop using Modbus does not work every time. This was fixed by using `client.write_coil(0, False)`  before triggering it again.  I don't move the arm using actions. I want to use ROS to do that. Below you can see the structure I planned to use.

```mermaid
graph TD

    A[Robot] -->|ROS Interface| C(Industrial PC)
    C--> F(Task and Path Planning)
    A-->| Modbus TCP|B(Safety PLC)
    B--> D(E-Stop)
    B--> E(Teach-Panel)
   
```

**Comment by felixmaisonneuve** [comment]
If by "resetting the robot" you mean clearing faults (to clear the emergency stop fault) so you can use the arm again, you can use the base's clear_faults service. We have an example of that here : https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_examples/src/full_arm/example_cartesian_poses_with_notifications.py#L81-L90

It uses the service defined above : https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_examples/src/full_arm/example_cartesian_poses_with_notifications.py#L41-L44

You can find something equivalent in C++ as well : https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_examples/src/full_arm/example_full_arm_movement.cpp#L81-L97

If this is not what you meant, can you elaborate on what you need and what you want to do?

Best,
Felix

**Comment by BBlumhofer** [comment]
Hi Felix, 
Yes, I meant clearing faults. Sorry for being to not precise on that.

To make it more clear what I am planning to do: 
- I have two parallel users: User 1 a Linux PC with ROS ( no issue there) User 2: A PLC to activate the E-Stop, apparent faults and manually move the robot
- My PLC only supports Modbus (no cpp/python or ROS)
- I need to activate the e-stop and clear the faults over Modbus while ROS controls the movement of the robot (Move it)
- In addition: If the ROS PC is unavailable, I need to move the Robot via an HMI connected to the PLC.  
- To control the robot and the safety functions only via ROS is not an option because of safety regulations

I hope this helps you to understand what the issue is.

Best,
Benjamin

**Comment by BBlumhofer** [comment]
Hi Felix, 

Ah okay, thank you this worked for me! Thanks for your help.

Best, 
Benjamin
