### ISSUE TITLE
Set TCP Values

### ISSUE THREAD

**Issue by miscz** [Kinovarobotics/kortex#18]
Where can I find the command to set other tool center point values (translation AND rotation) other than the default values for the Robotiq Gripper? In order to attach a custom tool we need to change those values.

Thanks a lot!

**Comment by alexvannobel** [comment]
Hi @miscz ,

Unfortunately the TCP of the Robotiq Gripper is hardcoded in the firmware's configuration files as of release 1.1.7, but the API function to change the TCP will be available in release 2.0, coming in mid-July.

Sorry for the inconvenience and I will make sure to update this issue whenever the TCP will be exposed in the API.

Best,
Alex

**Comment by miscz** [comment]
Hello!

It's almost August and I was wondering if there are any updates or a 2.0 release?

Best regards,
Michael

**Comment by alexvannobel** [comment]
Hi @miscz ,

The V&V on the arm's 2.0 firmware is finishing up this week for a targeted release early next week, if everything goes well.

Chers,
Alex

**Comment by miscz** [comment]
Nice! Thank you for your answer. I am excited to test the new functionalities!

**Comment by luangnp98** [comment]
Hello, there is an estimate to 2.0 firmware release?
Chers!

**Comment by alexvannobel** [comment]
Hi @miscz  and @LvOg118 ,

The [version 2.0 is now released](https://github.com/Kinovarobotics/kortex/releases/tag/v2.0.0).

You can now set the TCP from the WebApp or from the API with the [SetToolConfiguration](SetToolConfiguration) function of the ControlConfig service. 

I'll close this issue for now, but feel free to open a new one if there is anything with the functionality.

Thanks for your patience,
Best,
Alex
