### ISSUE TITLE
How to set ProtectionZone using API-C++, Is there some example codes?

### ISSUE THREAD

**Issue by gumpfly** [Kinovarobotics/kortex#23]
## Summary
Let the arm run in a certain area, do not enter the protection zone.

kortex API-C++2.0.0
Gen3 arm

**Comment by alexvannobel** [comment]
Hi @gumpfly ,
It's true that a proper Protection Zones example is missing (both for C++ and Python), so we'll work on adding that in the repo in the coming days.

For now, you can look into the [Base service documentation](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/summary_pages/Base.md) for the `CreateProtectionZone` function (to add a protection zone), the `UpdateProtectionZone` function (to modify an existing zone) and the `ReadProtectionZone` and `ReadAllProtectionZones` functions to retrieve the zones. The `DeleteProtectionZone` function may also be useful.

You can learn about the ProtectionZone data structure [in the corresponding documentation](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/messages/Base/ProtectionZone.md#).

I'll update this issue when the example will be pull-requested and when it will be added to the repo.

Best,
Alex

**Comment by alexvannobel** [comment]
Hi @gumpfly ,

We just added a [C++](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/examples/100-BaseGen3_overview/02-protection_zones_configuration.cpp) and a [Python](https://github.com/Kinovarobotics/kortex/blob/master/api_python/examples/100-BaseGen3_overview/02-protection_zones_configuration.py) example to show users how to use protection zones with the API.
I'll close the issue, but feel free to reopen it or create a new one if you encounter a problem!

Best,
Alex
