### ISSUE TITLE
how to read actuator fault states

### ISSUE THREAD

**Issue by colinator** [Kinovarobotics/kortex#33]
How can I read and interpret actuator fault states? 

I'm using the gen3 and low-level servoing modes. I see that ActuatorFeedback has plenty of information such as 'fault_bank_a' and 'fault_bank_b', etc. But I see no documentation as to what these things mean. Where is the documentation for all of this?

**Comment by simonferronforget** [comment]
Hello @colinator,

As stated in [ActuatorCyclic.Feedback](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/messages/ActuatorCyclic/Feedback.md
), you may find the different flags for **fault_bank_a** in this enum: [SafetyIdentifierBankA](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/enums/ActuatorConfig/SafetyIdentifierBankA.md).

As of today, **fault_bank_b** contains no flag for now.

Regards,
Simon
