### ISSUE TITLE
How to use depth stream on Python

### ISSUE THREAD

**Issue by eduardgr** [Kinovarobotics/kortex#40]
Hi,
I'm trying to get depth images from the KINOVA's Intel® RealSense™ Depth Module D410 using Python. However, the only way I can get it is using Gstreamer on Windows Command Prompt. I have already attempted to use cv2.VideoCapture, but this only works for the RGB camera. How can I code in  Python to obtain and use the depth stream in real-time the same way I do with the RGB camera?
*I tried to use the gstreamer package for Python, but it didn't work.
Python version: 3.6.7 
Firmware versions: 2.0.1-72
Kortex API version: 2.0.0
Thank you in advance!

**Comment by alexvannobel** [comment]
Hi @eduardgr ,
Really sorry, it seems like this issue slipped but #49 is a duplicate so I'll link it here and close this issue. Don't hesitate to reopen or answer if you have more questions.
Again, sorry this fell under our radar.
Best regards,
Alex
