### ISSUE TITLE
Joint Space Dynamics: Inertial Matrix, Centrifugal and Coriolis Terms and Gravity vector

### ISSUE THREAD

**Issue by mramonb** [Kinovarobotics/kortex#53]
## Description

We are implementing our own low-level torque control using BaseCyclic at PORT 10.001. Like commented in issue #38,  the torque control function used is:

tau_d = tau_task + Coriolis + gravity 

with 

tau_task = J'*wrench

So, in order to obtain the robot's compensation and the closed-loop, we need the following: Inertial Matrix, Centripetal and Coriolis Terms and Gravity vector. I've been looking at all the Kinova's information that is public and I haven't been able to find them, would it be possible that you provide me with this specific matrices? Or can you give me advice on how to obtain them to use this in C++ at low-level code?

Thank you very much in advance for you attention,

Marina

**Comment by alexvannobel** [comment]
Hi  @mramonb ,

Sorry for the delay.

I asked the control team and we don't expose the Inertial Matrix, Centripetal and Coriolis terms. 
The Gravity Vector is configurable from the WebApp or the API.

However, in the [ros_kortex repository](https://github.com/Kinovarobotics/ros_kortex) (`kortex_description` package) we do provide the URDF file for the robot, with which you should be able to calculate the parameters you need with a third-party library (like KDL or Robotics Library for example).

Hope this helps,
Alex
