### ISSUE TITLE
Low-Level Control: Where does the Velocity/Position feedback come from? absolute or incremental encoder?

### ISSUE THREAD

**Issue by whtqh** [Kinovarobotics/kortex#56]
Wondering if the absolute and incremental encoder both located in the output shaft?
When I get the velocity and position feedback using low-level control, it seems that velocity signal comes from the motor side. (The gearbox is elasticity?)

Just want to confirm it.
Thanks!

**Comment by simonferronforget** [comment]
Hi @whtqh, 
Sorry for the long delay.

Position AND velocity are from rotor (motor) incremental encoder.
Incremental position (rotor) is initialised with absolute encoder (this one on the output).

Hope this helps,
Simon
