### ISSUE TITLE
Joint readings bias

### ISSUE THREAD

**Issue by grizzi** [Kinovarobotics/kortex#58]
## Description

The joint values are off. The real robot joint positions do not match with the readings. I have been trying to reset factory settings, reset torque offset and every time I observe a little offset from the zero position. This is all using only the web interface. 
Here a picture of where the robot ends after executing the zero trajectory:
![IMG_20201110_175913](https://user-images.githubusercontent.com/26412496/98707388-4710c700-2380-11eb-8372-4c2e2a35153e.jpg)

## Version

Kortex Firmware : 2.2.0

Kortex Device : KIN = L53-CAB19-7Q00VI0S0000, Gen3 Ultra Lightweight Robot
Part Number: KR12086

## Expected behavior

At the zero position, the arm should be straight. 

## Any other information

The arm has been also used in low level servoing, using torque control.

**Comment by alexvannobel** [comment]
Hi @grizzi ,

Since this is not an issue with the code in the repository but more of a hardware / calibration issue, you should contact support@kinova.ca for assistance.

Best,
Alex
