### ISSUE TITLE
Links broken in the 

### ISSUE THREAD

**Issue by sbrisebois** [Kinovarobotics/kortex#7]
Hi, we notice a problem with links on the documentation : 
Branch Master, V 1.1.6

In the Quick Start for c++ those link are defect : 

Error management
API mechanism
Device routing
Transport / Router / Session / Notification

In the Quick Start for Pyhton user those link are defect : 
Error management
Device routing
Transport / Router / Session / Notification

Thanks,
Sylvain

**Comment by alexvannobel** [comment]
I added the missing files so now the links are working. 
Cheers,
Alex
