### ISSUE TITLE
How to get Jacobian matrix

### ISSUE THREAD

**Issue by atlas-jj** [Kinovarobotics/kortex#70]
## Summary

Is there any easy way to get the GEN3 Jacobian matrix just like the other robots like Franka Panda and WAM?

## Use case

Why is this feature needed?

Well, Jacobian matrix defines dot(e) = J * dot(q), it comes inherently from the robot's geometry model, it will be useful in many tasks like visual serving or reinforcement learning if RL practitioners care about more efficient training scenarios.

## Alternative

Should be best if provided within your kortex Python API.

If this feature is not implemented, do you have a workaround?

Nope.

## Possible issues

N/A

## Additional context

I'm running my thesis experiment on GEN3, so that's quite urgent. Will be appreciated if you can guide me to get sufficient parameters to compute the Jacobian.

**Comment by felixmaisonneuve** [comment]
Hi @atlas-jj,

Unfortunately, we do not provide our Jacobian matrix. 

You can use the third party library [Robotics Library](https://www.roboticslibrary.org/). However, we use a custom calibration to get a highier degree of precision that you won't be able to achieve using this library. 

I can also link this article that explains the algorithm used by our API : 
Phuoc, L. M., Lee, S. H., Kim, H. M., & Martinet, P. (2008). Damped least square based genetic algorithm with Gaussian distribution of damping factor for singularity-robust inverse kinematics. Journal of Mechanical Science and Technology, 22(7), 1330-1338.

I will close this issue, but if you have any more questions feel free to post them and I will answer them

Regards,
Felix
