### ISSUE TITLE
Kinova Gen3 lite:  Base joystick / expansion connector pinout usage

### ISSUE THREAD

**Issue by alexlt97** [Kinovarobotics/kortex#74]
Good afternoon,

I was wondering if there some documentation about how to control the connector pinouts of the Base joystick that are shown in table 4 of Gen3_lite_USER_GUIDE.pdf. The idea is to use the expansion GPI pins to communicate with sensors via ROS to Kinova Gen3 lite so I can use  really simple sensors, pneumatic sensors.

![table4](https://user-images.githubusercontent.com/48478107/132687562-44569087-7634-48db-bc4f-74796a62c012.png)

**Comment by felixmaisonneuve** [comment]
Hi @alexlt97 

Unfortunately, there is no usable connector in the base panel (except if you want to plug in a Xbox controller). 
It is not possible for you to communicate with connector pinout of the base joystick.

Sorry for the inconveniance,
Felix

**Comment by alexlt97** [comment]
But is clearly stated that you can use the expansion GPI pins to place a E-Stop button,  then why not similar inputs?

**Comment by felixmaisonneuve** [comment]
What you are asking has not been made accessible throught the Kortex API. You cannot communicate with any of the connectors in the base panel, the current behaviour is pre-programmed and cannot be changed by the user.

Sorry,
Felix
