### ISSUE TITLE
Is there any way to power on gen3 remotely?

### ISSUE THREAD

**Issue by yukizakisoh** [Kinovarobotics/kortex#76]
## Summary

Is there any way to power on gen3 remotely?

## Use case

Pressing the Emergency Stop button will power down the base as well as the arm, so I need to approach the robot and press the power button to restart it.  This can be very inconvenient and potentially dangerous.
Therefore, I would like to power on the robot remotely.

Is there any way to automatically start the robot when the power source is applied, or to turn it on remotely (like Wake-on-Lan for example)?

**Comment by felixmaisonneuve** [comment]
Hi @yukizakisoh,

Unfortunately, no. 

It is not possible to power on the arm remotely and you need to manually turn it on after an Emergency Stop. 

Sorry for the incoveniance,
Felix
